### ISSUE TITLE
[Bug] relation "conversations" does not exist

### ISSUE THREAD

**Issue by siddhijain47** [pinecone-io/chatbot-demo#15]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I run the command **npm run dev,** and redirected to UI, as I entered the text in textbox I am getting this error at backend terminal -
  name: 'SequelizeDatabaseError',
  parent: error: relation "conversations" does not exist
      at Parser.parseErrorMessage (/home/chatbot-demo/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/chatbot-demo/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/chatbot-demo/node_modules/pg-protocol/dist/parser.js:39:38)
      at TLSSocket.<anonymous> (/home/chatbot-demo/node_modules/pg-protocol/dist/index.js:11:42)
      at TLSSocket.emit (node:events:511:28)
      at addChunk (node:internal/streams/readable:332:12)
      at readableAddChunk (node:internal/streams/readable:305:9)
      at Readable.push (node:internal/streams/readable:242:10)
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 110,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'errors.go',
    line: '171',
    routine: 'NewUndefinedRelationError',
    sql: "SELECT entry, speaker, created_at FROM conversations WHERE user_id = 'roie' ORDER By created_at DESC LIMIT 10",
    parameters: undefined
  },
  original: error: relation "conversations" does not exist

![image](https://github.com/pinecone-io/chatbot-demo/assets/62420535/21a3c9f5-9af1-4593-bb75-6bc54d67ca0c)

### Expected Behavior

It should run smoothly

### Steps To Reproduce

Run npm run dev

### Environment

```markdown
- **OS**: linux
- **Language version**:Python 3.8.10
- **Pinecone client version**:
```

**Comment by PaulGwamanda** [comment]
The error means there is no schema named "conversations". You need to manually seed the migration in cockroachdb under data/migrations. Click Add Schema, Upload it as PostgresSQL, choose INT4 in INT type, then upload the file under ./db/dbinit.sql

After this, click migrate schema on top right then enter your database name
